algoritmo "retangulo"
var

   Altura, Base, Area, Perimetro, diagonal: Real

inicio

   Escreva("Base do retangulo: ")
   Leia(Base)
   Escreva("Altura do Retangulo: ")
   Leia(Altura)
   Area <- Base * Altura
   Perimetro <- 2 * (Base + Altura)
   Diagonal <- RaizQ(Exp(base, 2) + Exp(altura, 2))
   
   Escreval
   
   Escreval("AREA: ", Area:8:4)
   Escreval("PERIMETRO: ", Perimetro:8:4)
   Escreval("DIAGONAL: ", Diagonal:8:4)
   
fimalgoritmo
